dsl_name: base
max_length_only: false
output_dir: datasets/string_trans_100k
input_dir: null
seed: 0
num_demo: 20
min_str_len: 20
max_str_len: 30
maximum_attempt: 100
all_program: false
num_train: 100000
num_val: 5000
num_test: 5000
tol: 0.025
non_uniform: true
max_prog_len: 1
exec: PBE
num_try: 8
batch_size: 64
program_generation_ratio: 20
